import React from 'react'
import { defineMessages } from 'react-intl'
import { Code } from '../../index.styled'

export default defineMessages({
  stepOne: {
    id: 'HowItWorks.stepOne',
    defaultMessage: 'Follow the steps on ',
    description: 'The first step of HowItWorks section',
  },
  stepTwo: {
    id: 'HowItWorks.stepTwo',
    defaultMessage:
      'After a successful setup of your Web Monetized Wallet, add your payment pointer to Vanilla Admin.',
    description: 'The second step of HowItWorks section',
  },
  stepThree: {
    id: 'HowItWorks.stepThree',
    defaultMessage:
      'Copy your <code>{meta}</code> tag generated by Vanilla and place it to the <code>{head}</code> section of each page you want monetized.',
    description: 'The third step of HowItWorks section',
    values: {
      code: (value) => <Code>{value}</Code>,
      meta: `<meta>`,
      head: `<head>`,
    },
  },
  stepFour: {
    id: 'HowItWorks.stepFour',
    defaultMessage:
      'After completing the above steps you are able to verify every visitor request against the payment on your back-end server using our API endpoints. All payments go straight to your Web Monetization Wallet, after being identified by the Payment Pointer in Vanilla Admin.',
    description: 'The fourth step of HowItWorks section',
  },
  demoLink: {
    id: 'HowItWorks.demoLink',
    defaultMessage: 'Demo Application with Express server',
    description: 'The demo application link after step four',
  },
})
