import React from 'react';
import Text from '../../../../components/Text';
import Button from '../../../../components/Button';
import { Container, Code } from '../../index.styled';
import Snippet from '../Snippet';

export default ( {ILP_SERVER_URL, clientId} ) => {
  return (
    <Container>
      <ol>
        <Text mt="16px" as="li">
          Follow the steps on{' '}
          <Button
            href="https://webmonetization.org/docs/getting-started"
            as="a"
            target="_blank"
            noMargin
            secondary
            medium
          >
            webmonetization.org
          </Button>
          .
        </Text>
        <Text mt="16px" as="li">
          After a successful setup of your Web Monetized Wallet, add your
          payment pointer to Vanilla Admin.
        </Text>{' '}
        <Text mt="16px" as="li">
          Copy your <Code>{`<meta>`}</Code> tag generated by Vanilla and place
          it to the <Code>{`<head>`}</Code> section of each page you want
          monetized.
          <Snippet
            code={`<meta name="monetization" content="${ILP_SERVER_URL}/${clientId}" />`}
            language="html"
          />
        </Text>
        <Text mt="16px" as="li">
          After completing the above steps you are able to verify every visitor
          request against the payment on your back-end server using our API
          endpoints. All payments go straight to your Web Monetization Wallet,
          after being identified by the Payment Pointer in Vanilla Admin.
        </Text>
      </ol>
      
      <Button
        secondary
        medium
        as="a"
        href="https://github.com/vanilla-wm/vanilla-express-demo"
        target="_blank"
      >
        Demo Application with Express server
      </Button>
    </Container>
  );
}