import React from 'react'
import Text from '../../components/Text'
import Button from '../../components/Button'
import Snippet from './components/Snippet'
import { Container, Code } from './index.styled'
import UserContext from '../../config/UserContext'
import getConfig from 'next/config'
import InfoBox from './components/InfoBox'

const Heading = (props) => <Text as="h3" md mt="24px" {...props} />

export default () => {
  const { clientId, clientSecret } = React.useContext(UserContext)
  const {
    publicRuntimeConfig: { ILP_SERVER_URL, GRAPHQL_SERVER_URI },
  } = getConfig()

  return (
    <Container>
      <Text mt={24}>
        Vanilla provides{' '}
        <Text as="span" color="primary">
          Web Monetization
        </Text>{' '}
        verification features for applications that require higher level of
        flexibility.
      </Text>
      <InfoBox mt="16px">
        <Text mr="14px">💡</Text>
        <Text>
          Vanilla is currently working on implementing{' '}
          <Button
            medium
            target="_blank"
            color="primary"
            secondary
            as="a"
            href="https://interledger.org/rfcs/0039-stream-receipts/"
          >
            STREAM Receipts
          </Button>
          . STREAM Receipt is a proof of payment provided by Web Monetization
          Wallet.
        </Text>
      </InfoBox>

      <Heading>How it works</Heading>

      <ol>
        <Text mt="16px" as="li">
          Follow the steps on{' '}
          <Button
            href="https://webmonetization.org/docs/getting-started"
            as="a"
            target="_blank"
            noMargin
            secondary
            medium
          >
            webmonetization.org
          </Button>
          .
        </Text>
        <Text mt="16px" as="li">
          After a successful setup of your Web Monetized Wallet, add your
          payment pointer to Vanilla Admin.
        </Text>{' '}
        <Text mt="16px" as="li">
          Copy your <Code>{`<meta>`}</Code> tag generated by Vanilla and place
          it to the <Code>{`<head>`}</Code> section of each page you want
          monetized.
          <Snippet
            code={`<meta name="monetization" content="${ILP_SERVER_URL}/${clientId}" />`}
            language="html"
          />
        </Text>
        <Text mt="16px" as="li">
          After completing the above steps you are able to verify every visitor
          request against the payment on your back-end server using our API
          endpoints. All payments go straight to your Web Monetization Wallet,
          after being identified by the Payment Pointer in Vanilla Admin.
        </Text>
      </ol>
      <Button
        secondary
        medium
        as="a"
        href="https://github.com/vanilla-wm/vanilla-express-demo"
        target="_blank"
      >
        Demo Application with Express server
      </Button>
      <Heading>API Endpoints</Heading>
      <Text mt="8px">
        Endpoints provide interface for retrieving information about payments on
        your back-end server. Vanilla currently provides{' '}
        <Button
          secondary
          medium
          as="a"
          href={`https://${GRAPHQL_SERVER_URI}`}
          target="_blank"
        >
          GraphQL API.
        </Button>
      </Text>
      <Text mt="24px" semibold>
        Authentication
      </Text>
      <Text mt="4px">
        For requests authentication use generated <Code>clientID</Code> and{' '}
        <Code>clientSecret</Code>.
      </Text>
      <Snippet
        code={`
        Authorization: Basic Base64(<clientID>:<clientSecret>) 
      `}
        language="js"
      />
      <Text mt="20px">
        In each request include <Code>Authorization</Code> header provided
        below.
      </Text>
      <Snippet
        code={`
Authorization: Basic ${btoa(`${clientId}:${clientSecret}`)}`}
        language="js"
      />
      <Text mt="24px" semibold>
        Endpoint Proof
      </Text>
      <Text mt="4px" medium>
        Returns proof of payments for visitor's <Code>requestId</Code>
      </Text>
      <Text mt="20px" sm>
        GraphQL Query
      </Text>
      <Snippet
        code={`
query($requestId: String!) {
  proof(requestId: $requestId) {
    rate
    total
  }
}
`}
        language="js"
      />
      <Text mt="20px" sm>
        Example Response
      </Text>
      <Snippet
        code={`{
  proof: {
    total: 1340,
    rate: 1244.196843082637,
    metadata: {
      requestId: 'fbeb5308-87f9-4a33-9509-e1daf2e714b6',
      clientId: '031a4380-1905-46ba-84c6-f99e40a24506',
      contentId: null
    }
  }
}
`}
        language="js"
      />
      <Heading>Coming Soon</Heading>
      <ul>
        <Text as="li" mt="4px">
          Payments splitting
        </Text>
        <Text as="li" mt="4px">
          Music/Video Web Monetization features
        </Text>
        <Text as="li" mt="4px">
          Transaction history
        </Text>
        <Text as="li" mt="4px">
          Analytics
        </Text>
      </ul>
    </Container>
  )
}
